spring:
  application:
    name: swagger-service
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false
  data:
    mongodb:
      host: "mongo"
      port: 27017
      database: "amisno"
      username: "root"
      password: "toor"
      authentication-database: "admin"

server:
  context-path: '/v1'
  port: 8082

springfox:
  documentation:
    swagger:
      v2:
        path: '/api-docs'

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://amisno-infra-eureka:9103/eureka/
