spring:
  application:
    name: swagger-service
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "amisno"

server:
  context-path: '/v1'
  port: 8081

springfox:
  documentation:
    swagger:
      v2:
        path: '/api-docs'

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://amisno-infra-eureka:9103/eureka/
#
#ping-server:
#  ribbon:
#    eureka:
#      enabled: false # Disable Default Ping
#    listOfServers: localhost:8000,localhost:8001,localhost:8002,,localhost:8003
#    ServerListRefreshInterval: 15000

